// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoWebAPI.Models;

namespace TodoWebAPI.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20210415135928_initStructure")]
    partial class initStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("TodoWebAPI.Models.Todo.Person", b =>
                {
                    b.Property<uint>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("TodoWebAPI.Models.Todo.TodoItem", b =>
                {
                    b.Property<uint>("TodoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Due")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("ResponsiblePersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TodoItemId");

                    b.HasIndex("ResponsiblePersonId");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("TodoWebAPI.Models.Todo.TodoItem", b =>
                {
                    b.HasOne("TodoWebAPI.Models.Todo.Person", "Responsible")
                        .WithMany("ThingsTodo")
                        .HasForeignKey("ResponsiblePersonId");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("TodoWebAPI.Models.Todo.Person", b =>
                {
                    b.Navigation("ThingsTodo");
                });
#pragma warning restore 612, 618
        }
    }
}
